project:
  type: website

website:
  title: "Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
    - text: "Lab Website"
      href: https://developmental-psychopathology.lab.uiowa.edu

format:
  html:
    theme: cosmo
    css: ["styles.css", "includes/custom.css", "font/css/roboto.css"]
    toc: true
    toc-depth: 3
    toc-title: Contents
    toc-location: right
    number-sections: true
    code-fold: true
    df-print: paged
    code-tools: true
    link-external-newwindow: true
    include-in-header:
      - "includes/google_analytics.html"
    include-after-body:
      - "includes/footer.html"
