project:
  type: website

website:
  title: "Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-title: Contents
    toc-location: right
    number-sections: true
    code-fold: true
    df-print: paged
    link-external-newwindow: true
    include-in-header:
      - "includes/google_analytics.html"
    include-after-body:
      - "includes/footer.html"
